name: Spellcheck Action
on:
  push:
    paths:
      - "**/*.md"
      - ".spellcheck.yaml"
      - ".wordlist.txt"
      - ".github/workflows/spellcheck.yml"

permissions:
  contents: read

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Get all changed markdown files
      uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
      id: changed_files
      with:
        files: |
           **.md

    - name: Run Spellcheck
      id: spellcheck
      uses: rojopolis/spellcheck-github-actions@e619e00ca22f01ade9d73048dcd6518bedc552f2 # 0.63.0
      with:
        task_name: Markdown
        source_files: ${{ steps.changed_files.outputs.all_changed_files }}
        output_file: spellcheck-output.txt

